### PR TITLE
MAINT: add partial STDIO log

### PR DESCRIPTION
**Pull request by nawtrey**
* Add log with incomplete STDIO data for
testing partial data flags in main repo

### CODE REVIEW

**Comment by nawtrey** [comment]
This adds the log from an old darshan [issue](https://xgitlab.cels.anl.gov/darshan/darshan/-/issues/284#note_90972) about partial data. I think @carns will have to fill in some of the details on how the log was generated, but it's significant because of its partial module data.

**Comment by tylerjereddy** [comment]
ah yeah, Phil will have to press a button to allow the CI to run for first-time repo contributor (here and in other PR); apart from that, both seem "ok" at first glance, assuming the CI passes

**Comment by carns** [comment]
great, thanks!  I'll accept both this  and #18 once CI clears (I just mashed the button), and then commit a little more detailed readme description on top of each.

**Comment by nawtrey** [comment]
Sounds good, thanks

**Pull request merged**
