### PR TITLE
add empty log to logs repo

### PR DESCRIPTION
**Pull request by shanedsnyder**

### CODE REVIEW

**Comment by tylerjereddy** [comment]
Ah yeah, I think we have at least two issues open about this error in the main repo.

**Comment by shanedsnyder** [comment]
I think we should be able to move forward with this after merging https://github.com/darshan-hpc/darshan/pull/907

**Comment by tylerjereddy** [comment]
Maybe close/reopen this now that the matching PR has been merged

**Comment by shanedsnyder** [comment]
Tests look good now, I'll go ahead and merge this in

**Pull request merged**
