### PR TITLE
MAINT: move skew-io

### LINKED ISSUE #26: MAINT: skew-io folder in the wrong place
The `skiew-io` folder/data files are one level higher than all the other darshan data assets, which are stored in `darshan_logs` path. Apart from this being confusing, it also prevents us from using `get_lot_path` to retrieve those logs from an installed logs repo.

### PR DESCRIPTION
**Pull request by tylerjereddy**
Fixes #26

* make the `skew-io` folder data accessible to
main project by:
  - moving it under `darshan_logs` folder like the other
datasets
  - adding an `__init__.py`
  - using an `_` instead of a `-` in the folder name

### CODE REVIEW

**Comment by nawtrey** [comment]
The changes here look good, but we probably want to hold off on merging because the CI isn't running the logs here. With the changes in https://github.com/darshan-hpc/darshan/pull/671, we are no longer running all of the logs in the logs repo, including the logs being moved around here when I install this branch locally. The issue is the `e3sm_io_heatmap_...` logs come before the the `skew-..` logs and the entire test xfails when it hits them:

```
darshan-apmpi-2nodes-64mpi.darshan
imbalanced-io.darshan
nonmpi_dxt_anonymized.darshan
laytonjb_test1_id28730_6-7-43012-2131301613401632697_1.darshan
snyder_acme.exe_id1253318_9-27-24239-1515303144625770178_2.darshan
partial_data_dxt.darshan
e3sm_io_heatmap_and_dxt.darshan

**** tests xfail ****

e3sm_io_heatmap_only.darshan
treddy_mpi-io-test_id4373053_6-2-60198-9815401321915095332_1.darshan
skew-autobench-ior.darshan
skew-app.darshan
partial_data_stdio.darshan
runtime_and_dxt_heatmaps_diagonal_write_only.darshan
mpi-io-test.darshan
```

So it's getting about halfway through and then skipping the rest of the logs. Locally the logs do produce reports:
```
Report generated successfully. 
Saving report at location: /private/var/folders/w6/954gg3md5s10z0wl4fcq1fh0001221/T/pytest-of-nawtrey/pytest-92/test_main_all_logs_repo_files0/skew-autobench-ior_report.html

Report generated successfully. 
Saving report at location: /private/var/folders/w6/954gg3md5s10z0wl4fcq1fh0001221/T/pytest-of-nawtrey/pytest-92/test_main_all_logs_repo_files0/skew-app_report.html
```

Since the tests aren't parametrized over different logs, I think we will have to resort to skipping the darshan logs without xfailing. `pytest` might offer something a little more robust than a `continue`, but at the moment I don't think we want to be skipping half the logs.  

Additionally, I think it would help to add a `-v` flag to our CI `pytest` command so we can get the output stream from the summary report generation. That would allow us to confirm the CI is running all of the cases we are requesting since it prints out the report path.

**Comment by tylerjereddy** [comment]
Yes, we were already well aware of this in https://github.com/darshan-hpc/darshan/pull/671. I don't think we need to change the verbosity of our testsuite--just prioritize careful review/merging of the heatmap runtime fixes (can be done with "synthetic" data/logs and before/after evaluation of runtime results).

If you had concerns about this, it probably would have made much more sense to chime in in gh-671 and suggest that we opt for just using a `pass` for the violating cases to avoid case cutoffs (i.e., the decision/risk was made consciously, as I note over there).

**Comment by nawtrey** [comment]
> Yes, we were already well aware of this in [darshan-hpc/darshan#671](https://github.com/darshan-hpc/darshan/pull/671).

Yeah, I updated my comment because I realized you did mention this there. Either way I think it's still relevant here if we have the expectation that logs are being tested.

**Comment by tylerjereddy** [comment]
The cross-linked PR should deal with the complaints here, though the current situation is again by design, rather than oversight, as the original PR indicates..

**Review by nawtrey — APPROVED** [review]
Okay, the CI now covers the logs here (verified locally) so LGTM.

**Pull request merged**
