### PR TITLE
MAINT: add mpi_io_test file

### PR DESCRIPTION
**Pull request by tylerjereddy**
* add the log file requested by @carns on Slack,
along with a detailed `README` for how it was
produced

### CODE REVIEW

**Comment by tylerjereddy** [comment]
The CI failure needs investigating. Probably the CI here is not being maintained very actively, but should be fixed before merging this.

`Using legacy 'setup.py install' for matplotlib, since package 'wheel' is not installed.`

followed by a bunch of output.

I don't think a from-source build should be needed anymore, since 3.10 wheels should be available, but need to check on `seaborn` interaction issues with version bump maybe... feel free to help.

**Comment by carns** [comment]
Thanks @tylerjereddy .  Should we name the subdir `mpi_io_test_with_dxt` rather than `mpi_io_test` just so it's easier to see why it's notable at a glance?

Otherwise looks good.  I don't know how to debug the CI problem, though.

**Comment by tylerjereddy** [comment]
@carns 

> Should we name the subdir mpi_io_test_with_dxt rather than mpi_io_test just so it's easier to see why it's notable at a glance?

Yes, or even something more specific than that might be good--it is conceivable we'll use that `mpi_io_test.c` code again in the future for testing.

>  I don't know how to debug the CI problem, though.

Yeah, it probably involves trying a bunch of stuff related to unpinning the `matplotlib` version and seeing if `seaborn` is okay with that per https://github.com/darshan-hpc/darshan/issues/479.

**Comment by tylerjereddy** [comment]
@carns ok, CI is passing now (it was a transient connectivity issue), and I've adopted your suggested folder name

**Pull request merged**
