### PR TITLE
example log file with apmpi module active

### PR DESCRIPTION
**Pull request by sudheer9**
The log file was generated with Darshan 3.3.0 release, the log was generated on Theta using 128 processes (2 nodes with 64 processes)

### CODE REVIEW

**Comment by carns** [comment]
@sudheer9 , do you mind making two quick changes here:

- rename the actual log file itself to have a .darshan extension (so it is clearer that it is an original binary format log file)
- add your comment above about where the log was generated and at what scale to the readme

thanks!

**Comment by sudheer9** [comment]
@carns sure, I have made the suggested changes.

**Comment by carns** [comment]
I think the .log file is still in the commit?  Can you rm that or is there is a reason you need both?

**Comment by sudheer9** [comment]
No, we do not need the .log file, hopefully, this is correct now.

**Comment by carns** [comment]
thanks!

**Pull request merged**
